# FILL IN THE MISSING VALUES BELOW
alerting: 
  slack:
    enabled: true #  
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: Leantime
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 30s 
    conditions:
      - type: "status_code"
        expected: 200
        message: "Leantime is down! Please check and fix it."
      - type: "response_time"
        threshold: 1000 
        message: "Leantime is slow! Please check and fix it."
      - type: "keyword"
        keyword: "Leantime"
        message: "Leantime is not responding as expected! Please check and fix it."
    conditions:
    alerts:
      - type: slack 
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 60s 
    conditions:
      - type: "status_code"
        expected: 200
        message: "Gatus is down! Please check and fix it."
      - type: "response_time"
        threshold: 1000 
        message: "Gatus is slow! Please check and fix it."
      - type: "keyword"
        keyword: "Gatus"
        message: "Gatus is not responding as expected! Please check and fix it."
    conditions:
    alerts:
      - type: slack # WARN: DO NOT CHANGE THIS LINE
        description: "Sensei, Gatus is down! Please check and fix it."
# FILL IN THE MISSING VALUES BELOW
